dist: xenial

matrix:
  fast_finish: true

branches:
  only:
    - master

language: node_js
node_js:
  - '10.15.3'

services:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
  # https://benlimmer.com/2019/01/14/travis-ci-xvfb/
  - xvfb

addons:
  apt:
    packages:
      # Fix libgconf-2.so.4 errors
      # https://github.com/cypress-io/cypress/issues/4069#issuecomment-488315675
      - libgconf-2-4

cache:
  yarn: true
  timeout: 600
  directories:
    - $HOME/.electron
    - $HOME/.cache/electron-builder

script:
  - yarn lint
  - yarn test
  - yarn build
