matrix:
  fast_finish: true

branches:
  only:
    - master

language: node_js
node_js:
  - '10.15.3'

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache/electron-builder

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - yarn lint
  - yarn test
  - yarn build
