dist: trusty
os: linux

matrix:
  fast_finish: true

branches:
  only:
    - master

language: node_js
node_js:
  - '10.15.3'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb

cache:
  yarn: true
  timeout: 600
  directories:
    - $HOME/.electron
    - $HOME/.cache/electron-builder

script:
  - yarn lint
  - yarn test
  - yarn build
